services:
  cheshire-cat-core:
    build:
      context: ./core
    command:
    - python
    - -m
    - cat.main
    container_name: cheshire_cat_core_base
    environment:
    - PYTHONUNBUFFERED=1
    - WATCHFILES_FORCE_POLLING=true
    - CORE_HOST=${CORE_HOST:-localhost}
    - CORE_PORT=1866
    - CORE_USE_SECURE_PROTOCOLS=${CORE_USE_SECURE_PROTOCOLS:-}
    - API_KEY=${API_KEY:-}
    - LOG_LEVEL=${LOG_LEVEL:-INFO}
    - DEBUG=${DEBUG:-true}
    - SAVE_MEMORY_SNAPSHOTS=${SAVE_MEMORY_SNAPSHOTS:-false}
    ports:
    - 1866:80
    restart: unless-stopped
    volumes:
    - ./core:/app
version: '3.7'
